version: "{build}"

clone_folder: c:\gopath\src\github.com\philippgille\serve

# GitHub specific alternative to `clone_depth: <number>`
shallow_clone: true

environment:
  GOPATH: c:\gopath

stack: go 1.12

install:
  - go version
  - go env
  # Install tools
  - choco install upx

build_script:
  - go build -v
  - ps: build\build.ps1 -isAppVeyor

test_script:
  - .\serve.exe -v
  - .\serve.exe -t
  # Use PowerShell for glob. ".\" is necessary in this case.
  - ps: .\build\artifacts\serve_v*_Windows_x64.exe -v
  - ps: .\build\artifacts\serve_v*_Windows_x64.exe -t

artifacts:
- path: build\artifacts\*
