git:
  depth: 1

os: osx

addons:
  homebrew:
    packages:
    - go@1.12 # Currently the default Go version on the macOS build server is 1.10
    - upx
    update: true

env:
  - GO111MODULE=on

before_install:
  - go version
  - go env

script:
  - go build -v
  - build/build.sh
  # test
  - ./serve -h
  - ./serve -v
  - ./serve -t
  - VERSION=$(<VERSION)
  # Can't use "serve_v*_" for globbing on macOS by default
  - build/artifacts/serve_v${VERSION}_macOS_x64 -h
  - build/artifacts/serve_v${VERSION}_macOS_x64 -v
  - build/artifacts/serve_v${VERSION}_macOS_x64 -t
